{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "simple-pipeline.serviceAccountName" . }}
  labels:
{{ include "simple-pipeline.labels" . | indent 4 }}
{{- end -}}
